<?php
// module/Album/view/album/album/index.phtml:

$title = 'Projects';
$this->headTitle($title);
?>

<script src="js/ajax.js"></script>

<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    
    <a class="btn btn-success" href="<?= $this->url('prj', ['action' => 'add']) ?>"><span class="glyphicon glyphicon-plus-sign"></span>&nbsp;
                Add new project details&nbsp;<span class="glyphicon glyphicon-user"></span></a>
</p>

<!-- Content Section -->
<div class="container">
	<div class="row">
		<div class="col-md-12">
		
			<table class="table table-bordered table-striped table-hover">
			<tr>
			    <th>Project Name</th>
			    <th>Client Name</th>
			    <th>Project Manager</th>
			    <th>Start Date</th>
			    <th>&nbsp;</th>
			</tr>
			<?php foreach ($this->paginator as $prj) : ?>
			    <tr>
				<td><?= $this->escapeHtml($prj->prjname) ?></td>
				<td><?= $this->escapeHtml($prj->clientname) ?></td>
				<td><?= $this->escapeHtml($prj->prjmanagername) ?></td>
				<td><?= $this->escapeHtml($prj->prjstartdate) ?></td>
				<td>
				    <a class="btn btn-info" href="<?= $this->url('prj', ['action' => 'edit', 'id' => $prj->id]) ?>">
				    <span class="glyphicon glyphicon-pencil"></span>&nbsp;Edit</a>
				    
				    <a class="btn btn-danger" href="<?= $this->url('prj', ['action' => 'delete', 'id' => $prj->id]) ?>">
				    <span class="glyphicon glyphicon-trash"></span>&nbsp;Delete</a>
				</td>
			    </tr>
			<?php endforeach; ?>
				<tr> <td colspan="6" class="records_content"></td></tr>
			</table>
			<center>
			<?= $this->paginationControl(
			    // The paginator object:
			    $this->paginator,
			    // The scrolling style:
			    'sliding',
			    // The partial to use to render the control:
			    'partial/paginator',
			    // The route to link to when a user clicks a control link:
			    ['route' => 'prj']
			) ?>
			</center>
		
		<div class="pull-right">
		<button class="btn btn-success" data-toggle="modal" data-target="#add_new_record_modal">Ajax Add New Record</button>
		</div>
	</div>

</div>
<!-- /Content Section -->



<!-- Modal -->
<div class="modal fade" id="add_new_record_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
<div class="modal-dialog" role="document">
<div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
<h4 class="modal-title" id="myModalLabel">Add New Record</h4>
</div>
<div class="modal-body">

<form id="myform" name="myform" method="post">

<div class="form-group">
<label for="PrjName">Project Name</label>
<input type="text" id="prjname" name="prjname" placeholder="Project Name" class="form-control" />
</div>
 
<div class="form-group">
<label for="clientname">Client Name</label>
<input type="text" id="clientname" name="clientname" placeholder="Client Name" class="form-control" />
</div>

<div class="form-group">
<label for="prjmanagername">Project Manager Name</label>
<input type="text" id="prjmanagername" name="prjmanagername" placeholder="Project Manager Name" class="form-control" />
</div>
 
<div class="form-group">
<label for="prjstartdate">Start Date</label>
<input type="text" id="prjstartdate" name="prjstartdate" placeholder="mm/dd/yyyy" class="form-control" />
</div>

</div>
<div class="modal-footer">
<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
<button type="button" class="btn btn-primary" onclick="addRecord()">Add Record</button>
</div>

</form>

</div>
</div>
</div>
